apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
  namespace: prod
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: prod
data:
  APP_MODE: "demo"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-writer
  namespace: prod
  labels:
    app: demo-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-writer
  template:
    metadata:
      labels:
        app: demo-writer
      # если не включали default-volumes-to-fs-backup, эта аннотация обязательна:
      annotations:
        backup.velero.io/backup-volumes: demo-data
    spec:
      containers:
        - name: writer
          image: busybox:1.36
          command: ["/bin/sh","-c"]
          args:
            - |
              echo "start $(date -Iseconds)" >> /data/log.txt;
              while true; do
                date -Iseconds >> /data/log.txt;
                sleep 5;
              done
          volumeMounts:
            - name: demo-data
              mountPath: /data
      volumes:
        - name: demo-data
          persistentVolumeClaim:
            claimName: demo-pvc

