apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-cron
  namespace: velero
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velero-cron-role
  namespace: velero
rules:
  - apiGroups: ["velero.io"]
    resources: ["backups"]
    verbs: ["create","get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero-cron-rb
  namespace: velero
subjects:
  - kind: ServiceAccount
    name: velero-cron
    namespace: velero
roleRef:
  kind: Role
  name: velero-cron-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-prod-ns
  namespace: velero
spec:
  schedule: "15 */6 * * *"   # каждые 6 часов (в 15 минут)
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: velero-cron
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: bitnami/kubectl:1.29
              command: ["/bin/sh","-c"]
              args:
                - |
                  cat <<'EOF' | kubectl create -f -
                  apiVersion: velero.io/v1
                  kind: Backup
                  metadata:
                    generateName: prod-cron-
                    namespace: velero
                  spec:
                    includedNamespaces:
                      - prod
                    ttl: 336h0m0s
                    defaultVolumesToFsBackup: true
                    # минимизация: секреты исключены из бэкапа (при необходимости хранить секреты — использовать внешний secret-store/шифрование бакета)
                    excludedResources:
                      - secrets

